import _ from 'lodash';
import Bluebird from 'bluebird';

import * as Tasks from '../../website/server/models/task';
import { model as Challenges } from '../../website/server/models/challenge';

let tasks = [
  {
    "shortName": "Power Quality and Reliability",
    "question": "Promptly restore power after an outage",
    "text": "**Your Role in More Prompt Restoration.** Restoring power promptly after an outage is a big job that involves all employees regardless of their role. Note an example of how you specifically can support more prompt restoration in the pop up screen.",
    "notes": "",
    "repeatable": "No",
    "value": 20,
    "challengeId": "de61fb54-d200-42bc-a917-70b70d8cd408",
    "type": "habit",
    down: false,
  },
  {
    "shortName": "Power Quality and Reliability",
    "question": "Provide quality electric power (spikes, drops, surges)",
    "text": "**We Power Lives Every Day.** [Watch this video]( https://drive.google.com/file/d/0B-DpKyEwPn_SbjI0MUlDZGdXc0E/view?usp=sharing) to see how one of our teams worked together to restore a nursing home. If you have a story, share it with us in an email to <ExperiencingComEd@exeloncorp.com>.",
    "notes": "",
    "repeatable": "No",
    "value": 5,
    "challengeId": "de61fb54-d200-42bc-a917-70b70d8cd408",
    "type": "habit",
    down: false,
  },
  {
    "shortName": "Power Quality and Reliability",
    "question": "Avoid brief interruptions of 5 minutes or less",
    "text": "**Outage vs Interruption Video.** Understand the difference between a brief interruption (5 minutes or less) and a lengthy outage (more than 5 minutes). Submit a short video to <ExperiencingComEd@exeloncorp.com> describing the differences and why they might happen. *Approved videos may be posted to social media*.",
    "notes": "Take the lead! Complete this task worth 50 points!",
    "repeatable": "No",
    "value": 50,
    "challengeId": "de61fb54-d200-42bc-a917-70b70d8cd408",
    "type": "habit",
    down: false,
  },
  {
    "shortName": "Price",
    "question": "Total monthly cost of your electric service",
    "text": "**Take a picture of yourself** next to an appliance with a sign showing how much it costs to run it in a normal month. Post it to your favorite social media channel like [Facebook](https://www.facebook.com/), [Twitter](https://twitter.com/), [Instagram](https://www.instagram.com/) or [Pinterest](https://www.pinterest.com/) and use tags *@ComEd, #DollarPower, #Emp*.",
    "notes": "Selfie? Yes please!",
    "repeatable": "No",
    "value": 40,
    "challengeId": "033c5270-0cc6-4a51-b62d-e61450d1fde8",
    "type": "habit",
    down: false,
  },
  {
    "shortName": "Price",
    "question": "Effort to help you manage your monthly usage",
    "text": "**AMI Benefits?** Can you describe the benefits of a smart meter (AMI) to a customer? Write your explanation to a customer in the pop-up.",
    "notes": "",
    "repeatable": "No",
    "value": 20,
    "challengeId": "033c5270-0cc6-4a51-b62d-e61450d1fde8",
    "type": "habit",
    down: false,
  },
  {
    "shortName": "Billing and Pay",
    "question": "Variety of methods to pay your bill",
    "text": "**Ways to Pay on social media!** Post a few of the [convenient ways to pay your ComEd bill](https://www.comed.com/MyAccount/MyBillUsage/Pages/PayMyBill.aspx) to social media and use tags *@ComEd, #Waystopay, #Emp*.",
    "notes": "",
    "repeatable": "No",
    "value": 20,
    "challengeId": "cb0c29f1-7468-4126-876e-f6b97881016a",
    "type": "habit",
    down: false,
  },
  {
    "shortName": "Billing and Pay",
    "question": "Ease of paying your bill",
    "text": "**EPAY signup!** Encourage a friend or family member to [Sign up for EPAY](https://www.comed.com/MyAccount/MyBillUsage/Pages/ARCHIVE/PayMyBill.aspx). If you haven't signed up yet, do so.",
    "notes": "Easy points with ePay!",
    "repeatable": "No",
    "value": 20,
    "challengeId": "cb0c29f1-7468-4126-876e-f6b97881016a",
    "type": "habit",
    down: false,
  },
  {
    "shortName": "Corporate Citizenship",
    "question": "Involvement in local charities and civic organizations",
    "text": "**Participate in a ComEd Charity or Organization Event!** [Log your volunteer hours](https://energyforthecommunity.angelpointsevs.com/handlers/login.aph), and download the [Energy for the Community Mobile App](http://myexelon.exeloncorp.com/Exelon/CommunityRelations/Documents/Download%20Mobile%20App-%202%20pager.pdf).",
    "notes": "Log your hours, load up on 50 points!",
    "repeatable": "Yes",
    "value": 50,
    "challengeId": "e1661681-d25c-4471-a4cb-e6eb25915f66",
    "type": "habit",
    down: false,
  },
  {
    "shortName": "Corporate Citizenship",
    "question": "Involvement in local charities and civic organizations",
    "text": "**Attend any Volunteer Event** wearing a ComEd t-shirt and post a picture of yourself on social media like [Facebook](https://www.facebook.com/), [Twitter](https://twitter.com/), [Instagram](https://www.instagram.com/) or [Pinterest](https://www.pinterest.com/). Don't forget to bring some of your coworkers too! Make sure to use tags *@ComEd, #ComEdVolunteers, or #WeAreComEd*!",
    "notes": "You’ll look great in ComEd Red and at the top of the leaderboard with these easy 40 points.",
    "repeatable": "Yes",
    "value": 40,
    "challengeId": "e1661681-d25c-4471-a4cb-e6eb25915f66",
    "type": "habit",
    down: false,
  },
  {
    "shortName": "Corporate Citizenship",
    "question": "Efforts to develop energy supply plans for the future",
    "text": "**Future Energy Jobs Act.** What’s exciting at ComEd? The future Energy Jobs Act. [Read about this law]( http://teamapps.exeloncorp.com/sites/ITAcademy/Public%20Documents/FutureEnergyJobsAct.pdf) and note what interests you most in the pop up.",
    "notes": "Read all about it for 50 points!",
    "repeatable": "No",
    "value": 50,
    "challengeId": "e1661681-d25c-4471-a4cb-e6eb25915f66",
    "type": "habit",
    down: false,
  },
  {
    "shortName": "Communications",
    "question": "Efforts to communicate changes that might affect you",
    "text": "**Powering Lives Network Story.** The Powering Lives Network is a great resource for getting engaging and meaningful content in front of our customers, particularly when it comes to changes or innovations in our business that could affect them. Submit your idea for a story in the pop up.",
    "notes": "Write your way to stardom! Submit your ideas and find fame on the leaderboards with 30 points!",
    "repeatable": "No",
    "value": 30,
    "challengeId": "0afd0d36-39e4-49a0-ad2f-fa7479df99e9",
    "type": "habit",
    down: false,
  },
  {
    "shortName": "Communications",
    "question": "Usefulness of suggestions to reduce your monthly bill",
    "text": "**Post Bill Insert on Social Media!** Look for an Energy Efficiency insert in your monthly bill.  Take a picture and post it to social media. Tell your friends they could be saving too!",
    "notes": "These points might as well be hand-delivered to you! Be sure to scoop them up.",
    "repeatable": "No",
    "value": 15,
    "challengeId": "0afd0d36-39e4-49a0-ad2f-fa7479df99e9",
    "type": "habit",
    down: false,
  },
  {
    "shortName": "Communications",
    "question": "Communicating how to be safe around electricity",
    "text": "**Rap about it!** Access your inner poet/singer and write a rap about safety. Record an individual or team rap and send it to <ExperiencingComEd@exeloncorp.com>. *Best raps will be shared on social media and employee screens!*",
    "notes": "Tap in to your creative side for 50 points!",
    "repeatable": "No",
    "value": 50,
    "challengeId": "0afd0d36-39e4-49a0-ad2f-fa7479df99e9",
    "type": "habit",
    down: false,
  },
  {
    "shortName": "Customer Service",
    "question": "Ease of navigating the website (web)",
    "text": "**Follow ComEd** on [Facebook](https://www.facebook.com/ComEd/), [Twitter](https://twitter.com/ComEd), [Instagram](https://www.instagram.com/commonwealthedison/), [LinkedIn](https://www.linkedin.com/company/comed) or [YouTube](https://www.youtube.com/user/CommonwealthEdison).",
    "notes": "You’re one click away from 10 points!",
    "repeatable": "No",
    "value": 10,
    "challengeId": "d9f86ef5-46ea-4634-acee-ac4aff67b89d",
    "type": "habit",
    down: false,
  },
  {
    "shortName": "Customer Service",
    "question": "Representative's concern for your needs",
    "text": "**CARE for Customers.** Review how we [CARE for our customers](http://www.comed.com/MyAccount/CustomerSupport/Pages/AssistancePrograms.aspx) who need assistance at ComEd!",
    "notes": "Take pride in how ComEd is helping people and treat yourself to 20 points.",
    "repeatable": "No",
    "value": 20,
    "challengeId": "d9f86ef5-46ea-4634-acee-ac4aff67b89d",
    "type": "habit",
    down: false,
  },
];

let tasks2 = [
  {
    "shortName": "Power Quality and Reliability",
    "question": "Provide quality electric power (spikes, drops, surges)",
    "text": "**Prevent a Possible Outage** Always look at the bigger picture, not just what you're on the job to do. Identify a possible problem at a home or with equipment that could lead to an outage. Proactively report it to the proper department. Note your action in the pop up screen.",
    "notes": "",
    "repeatable": "No",
    "value": 40,
    "challengeId": "de61fb54-d200-42bc-a917-70b70d8cd408",
    "type": "habit",
    "down": false,
  },
  {
    "shortName": "Power Quality and Reliability",
    "question": "Avoid lengthy outages of more than 5 minutes",
    "text": "**Preventative Outages Video.** Submit a short video to <ExperiencingComEd@exeloncorp.com> describing two examples of lengthy outages and why these are necessary to avoid future outages.",
    "notes": "",
    "repeatable": "No",
    "value": 50,
    "challengeId": "de61fb54-d200-42bc-a917-70b70d8cd408",
    "type": "habit",
    "down": false,
  },
  {
    "shortName": "Price",
    "question": "Total monthly cost of your electric service",
    "text": "**Estimate Your Bill.** Do you wonder what your electric bill will be every month? Estimate your own bill using [ComEd's Bill Estimator Tool]( https://secure.comed.com/MyAccount/MyService/CustomerChoice/Pages/BillEstimatorTool.aspx).",
    "notes": "",
    "repeatable": "No",
    "value": 20,
    "challengeId": "033c5270-0cc6-4a51-b62d-e61450d1fde8",
    "type": "habit",
    "down": false,
  },
  {
    "shortName": "Price",
    "question": "Effort to help you manage your monthly usage",
    "text": "**Schedule Free Energy Assessment.** Do you know that you are eligible for a free home energy assessment? [Schedule one now](https://www.comed.com/Assessment).",
    "notes": "Get it on the calendar for 40 points!",
    "repeatable": "No",
    "value": 40,
    "challengeId": "033c5270-0cc6-4a51-b62d-e61450d1fde8",
    "type": "habit",
    "down": false,
  },
  {
    "shortName": "Billing and Pay",
    "question": "Amount of time given to pay your bill",
    "text": "**'My Account' Set Up.** Log into [My Account](https://secure.comed.com/pages/login.aspx) and set up an *Alert*, set a preference in the *Preference Center* or set up a *Payment Due Reminder*.",
    "notes": "",
    "repeatable": "No",
    "value": 10,
    "challengeId": "cb0c29f1-7468-4126-876e-f6b97881016a",
    "type": "habit",
    "down": false,
  },
  {
    "shortName": "Billing and Pay",
    "question": "Ease of paying your bill",
    "text": "**Explain Payment Options.** Learn about the [flexible payment options](https://www.comed.com/SiteCollectionDocuments/MyAccount/MyBillUsage/BillInserts/2017/Mar2017eBill.pdf) offered by ComEd including *minimum payment option, deferred payment agreement*, and *budget Billing and Pay*. Note in the pop up how you would best explain payment options to a customer.",
    "notes": "",
    "repeatable": "No",
    "value": 30,
    "challengeId": "cb0c29f1-7468-4126-876e-f6b97881016a",
    "type": "habit",
    "down": false,
  },
  {
    "shortName": "Corporate Citizenship",
    "question": "Efforts to develop energy supply plans for the future",
    "text": "**Attend a Community Event.** Use the [Community Events Calendar](https://www.comed.com/SafetyCommunity/Community/Pages/CommunityEventsCalendar.aspx) to attend a scheduled event. Note where you went and what you learned in the pop up.",
    "notes": "Show up and up your score a full 40 points!",
    "repeatable": "Yes",
    "value": 40,
    "challengeId": "e1661681-d25c-4471-a4cb-e6eb25915f66",
    "type": "habit",
    "down": false,
  },
  {
    "shortName": "Corporate Citizenship",
    "question": "Variety of energy efficiency programs offered",
    "text": "**Learn About Energy Efficiency Programs.** Educate yourself on all of the Energy Efficiency programs offered by ComEd (*Rebates and Discounts*). Tell your friends.",
    "notes": "Easy EE points!",
    "repeatable": "No",
    "value": 15,
    "challengeId": "e1661681-d25c-4471-a4cb-e6eb25915f66",
    "type": "habit",
    "down": false,
  },
  {
    "shortName": "Communications",
    "question": "Keeping you informed about keeping your costs low",
    "text": "**Post Efficiency Tips on Social Media.** What energy efficiency tips does your family use? Post them on social media like [Facebook](https://www.facebook.com/), [Twitter](https://twitter.com/), [Instagram](https://www.instagram.com/) or [Pinterest](https://www.pinterest.com/), and tag *#WaysToSave*.",
    "notes": "Got a good tip? Share it and we’ll share 15 points with you.",
    "repeatable": "No",
    "value": 15,
    "challengeId": "0afd0d36-39e4-49a0-ad2f-fa7479df99e9",
    "type": "habit",
    "down": false,
  },
  {
    "shortName": "Communications",
    "question": "Communicating how to be safe around electricity",
    "text": "**Safe Around Electricity.** Tell us about a time you exercised caution around electricity and why. Note how you are safe around electricity in the pop up.",
    "notes": "Keep your score safe with a quick 20 points.",
    "repeatable": "No",
    "value": 20,
    "challengeId": "0afd0d36-39e4-49a0-ad2f-fa7479df99e9",
    "type": "habit",
    "down": false,
  },
  {
    "shortName": "Communications",
    "question": "Creating messages that get your attention",
    "text": "**Submit a Customer Story** to the <ExperiencingComEd@exeloncorp.com> mailbox. *Submissions may be published on the [Powering Lives Network](https://poweringlives.comed.com/) or Underground Intel.*",
    "notes": "",
    "repeatable": "No",
    "value": 30,
    "challengeId": "0afd0d36-39e4-49a0-ad2f-fa7479df99e9",
    "type": "habit",
    "down": false,
  },
  {
    "shortName": "Customer Service",
    "question": "Ease of navigating the website (web)",
    "text": "**Favorite App Feature.** Download the [ComEd app](https://www.comed.com/MyAccount/CustomerSupport/Pages/MobileApp.aspx), explore the app and note your favorite feature in the pop up.",
    "notes": "",
    "repeatable": "No",
    "value": 20,
    "challengeId": "d9f86ef5-46ea-4634-acee-ac4aff67b89d",
    "type": "habit",
    "down": false,
  },
  {
    "shortName": "Customer Service",
    "question": "Representative's knowledge",
    "text": "**How do You Power Lives?** We are all in  Customer Service even if you don't deal directly with the customers. What you do powers lives. Review the [Leadership and Values tab](https://www.comed.com/AboutUs/Pages/LeadershipValues.aspx) at ComEd.com then tell us how you POWER LIVES in the pop up.",
    "notes": "Power lives and power up your score with this fun task.",
    "repeatable": "No",
    "value": 20,
    "challengeId": "d9f86ef5-46ea-4634-acee-ac4aff67b89d",
    "type": "habit",
    "down": false,
  },
];

let tasks3 = [
  {
    "shortName": "Power Quality and Reliability",
    "question": "Keep you informed about an outage",
    "text": "**Outage Alert Signup.** Encourage a friend or family members to sign up for outage alerts.  Or sign up yourself! Sign up is available via  [Twitter](https://twitter.com/ComEd), the *Preference Center* in [My Account](https://secure.comed.com/pages/login.aspx), or the [ComEd app](https://www.comed.com/MyAccount/CustomerSupport/Pages/MobileApp.aspx).",
    "notes": "Take advantage of these easy points!",
    "repeatable": "No",
    "value": 15,
    "challengeId": "de61fb54-d200-42bc-a917-70b70d8cd408",
    "type": "habit",
    "down": false,
  },
  {
    "shortName": "Power Quality and Reliability",
    "question": "Keep you informed about an outage",
    "text": "**Use social media!** Encourage followers to sign up for outage alerts in your social media feeds like [Facebook](https://www.facebook.com/), [Twitter](https://twitter.com/), [Instagram](https://www.instagram.com/) or [Pinterest](https://www.pinterest.com/). Don't forget to mention *@ComEd & #EMP*.",
    "notes": "Take advantage of these easy points!",
    "repeatable": "No",
    "value": 10,
    "challengeId": "de61fb54-d200-42bc-a917-70b70d8cd408",
    "type": "habit",
    "down": false,
  },
  {
    "shortName": "Price",
    "question": "Effort to help you manage your monthly usage",
    "text": "**Post a Picture!** Post a picture of yourself and a friend discussing your ComEd bill or their smart meter to a social media account like [Facebook](https://www.facebook.com/), [Twitter](https://twitter.com/), [Instagram](https://www.instagram.com/) or [Pinterest](https://www.pinterest.com/).  Be sure to tag *@ComEd and not have any sensitive information showing!*",
    "notes": "Get camera ready for 30 points!",
    "repeatable": "No",
    "value": 30,
    "challengeId": "033c5270-0cc6-4a51-b62d-e61450d1fde8",
    "type": "habit",
    "down": false,
  },
  {
    "shortName": "Price",
    "question": "Ease of understanding your pricing options",
    "text": "**Customer Choice** is the right of all customers in the ComEd service area to choose their electric supplier. Read these [four articles on Customer Choice](https://www.comed.com/MyAccount/MyService/Pages/CustomerChoice.aspx) to be better prepared to explain to friends, family & customers.",
    "notes": "",
    "repeatable": "No",
    "value": 20,
    "challengeId": "033c5270-0cc6-4a51-b62d-e61450d1fde8",
    "type": "habit",
    "down": false,
  },
  {
    "shortName": "Billing and Pay",
    "question": "Usefulness of information on your bill",
    "text": "**Bill Feedback.** Look at your ComEd bill and tell us what you think customers may find easy or hard to understand.  Make a note of your findings in the pop up.",
    "notes": "",
    "repeatable": "No",
    "value": 30,
    "challengeId": "cb0c29f1-7468-4126-876e-f6b97881016a",
    "type": "habit",
    "down": false,
  },
  {
    "shortName": "Corporate Citizenship",
    "question": "Involvement in local charities and civic organizations",
    "text": "**Join an Employee Resource Group.** Employee Resource Groups are a great networking opportunity - join one that is meaningful to you. Note which one(s) you are a member of in the pop up.",
    "notes": "",
    "repeatable": "No",
    "value": 20,
    "challengeId": "e1661681-d25c-4471-a4cb-e6eb25915f66",
    "type": "habit",
    "down": false,
  },
  {
    "shortName": "Corporate Citizenship",
    "question": "Actions to take care of the environment",
    "text": "**Participate in Efficiency Program.** Participate in one or more of [ComEd's Energy Efficiency  programs](https://www.comed.com/WaystoSave/ForYourHome/Pages/RebatesDiscounts.aspx) (*Fridge recycling, FREE home energy assessments, lighting discounts, etc.*)",
    "notes": "",
    "repeatable": "Yes",
    "value": 30,
    "challengeId": "e1661681-d25c-4471-a4cb-e6eb25915f66",
    "type": "habit",
    "down": false,
  },
  {
    "shortName": "Communications",
    "question": "Creating messages that get your attention",
    "text": "**Watch Videos!** Check out a few videos on the [Commonwealth Edison YouTube Channel](https://www.youtube.com/user/CommonwealthEdison). You'll be surprised at how much you can learn!",
    "notes": "These points are too good to miss!",
    "repeatable": "No",
    "value": 15,
    "challengeId": "0afd0d36-39e4-49a0-ad2f-fa7479df99e9",
    "type": "habit",
    "down": false,
  },
  {
    "shortName": "Customer Service",
    "question": "Ease of navigating the website (web)",
    "text": "**My Account Feedback.** Sign up for [My Account](https://secure.comed.com/pages/login.aspx), explore and provide us with feedback about your experience with My Account.",
    "notes": "You’re a ComEd customer too! Help us help you and you’ll get 20 points for your efforts.",
    "repeatable": "No",
    "value": 20,
    "challengeId": "d9f86ef5-46ea-4634-acee-ac4aff67b89d",
    "type": "habit",
    "down": false,
  },
  {
    "shortName": "Customer Service",
    "question": "Courtesy of representative",
    "text": "**Learn About CX (Customer Experience).** ComEd has great resources with lots of learning opportunities. [Read an article](http://www.customerbliss.com/category/customers-as-assets/) on a topic that you're interested in on fostering good customer experiences.",
    "notes": "",
    "repeatable": "No",
    "value": 30,
    "challengeId": "d9f86ef5-46ea-4634-acee-ac4aff67b89d",
    "type": "habit",
    "down": false,
  }
];

let tasks4 = [
  {
    "shortName": "Power Quality and Reliability",
    "question": "Supply electricity in hot/cold temperatures",
    "text": "**Customer Support in Extreme Weather.** An outage during extreme temperatures can be inconvenient for customers, tell us how you supported a customer during extreme weather.  Note your story in the pop up screen.",
    "notes": "Brrr-its cold out there, but warm our hearts with your customer story!",
    "repeatable": "No",
    "value": 30,
    "challengeId": "de61fb54-d200-42bc-a917-70b70d8cd408",
    "type": "habit",
    "down": false,
  },
  {
    "shortName": "Power Quality and Reliability",
    "question": "Keep you informed about an outage",
    "text": "**List Outage Communications.** We have many ways to [communicate outages to our customers](https://www.comed.com/Outages/ReportAnOutage/Pages/default.aspx). Note the ways ComEd informs a customer about outages in the pop up.",
    "notes": "",
    "repeatable": "Yes",
    "value": 20,
    "challengeId": "de61fb54-d200-42bc-a917-70b70d8cd408",
    "type": "habit",
    "down": false,
  },
  {
    "shortName": "Price",
    "question": "Fairness of pricing",
    "text": "**Go Shopping!** Visit [ComEdMarketplace.com](https://www.comedmarketplace.com/) and tell your family and friends about the great discounts and rebates offered there. *No purchase necessary.*",
    "notes": "",
    "repeatable": "No",
    "value": 20,
    "challengeId": "033c5270-0cc6-4a51-b62d-e61450d1fde8",
    "type": "habit",
    "down": false,
  },
  {
    "shortName": "Price",
    "question": "Availability of pricing options that meet your needs",
    "text": "**Tell a Friend.** Tell a friend or family member about one of [ComEd's Pricing Options](https://www.comed.com/MyAccount/MyBillUsage/Pages/OptionalPricingPrograms.aspx) such at *Peak Time Savings*, *Hourly Pricing* and *A/C Cycling*. Which program was of interest to them and why? Let us know in the pop up.",
    "notes": "",
    "repeatable": "No",
    "value": 30,
    "challengeId": "033c5270-0cc6-4a51-b62d-e61450d1fde8",
    "type": "habit",
    "down": false,
  },
  {
    "shortName": "Billing and Pay",
    "question": "Variety of methods to pay your bill",
    "text": "**Share ComEd Mobile App.** If you haven't already, download the [ComEd mobile app](https://www.comed.com/MyAccount/CustomerSupport/Pages/MobileApp.aspx) to your phone today.  Encourage a friend and family members to do so, too!",
    "notes": "Get the app, get the points!",
    "repeatable": "No",
    "value": 30,
    "challengeId": "cb0c29f1-7468-4126-876e-f6b97881016a",
    "type": "habit",
    "down": false,
  },
  {
    "shortName": "Billing and Pay",
    "question": "Usefulness of information on your bill",
    "text": "**eBill Sign Up.** [Sign up for eBill](https://www.comed.com/MyAccount/MyBillUsage/Pages/ARCHIVE/PayMyBill.aspx) to make it convenient and easy to view and pay your bill on the go!",
    "notes": "Sign up and rack up 40 points!",
    "repeatable": "No",
    "value": 40,
    "challengeId": "cb0c29f1-7468-4126-876e-f6b97881016a",
    "type": "habit",
    "down": false,
  },
  {
    "shortName": "Corporate Citizenship",
    "question": "Involvement in local charities and civic organizations",
    "text": "**Make a Charitable Donation.** Join the company in the support of eligible charitable organizations. Make a donation to your favorite charity and add the match in the [Matching Gifts](https://www.easymatch.com/exelongiving) section of the Exelon Foundation website.",
    "notes": "Giving back gets you big points!",
    "repeatable": "No",
    "value": 50,
    "challengeId": "e1661681-d25c-4471-a4cb-e6eb25915f66",
    "type": "habit",
    "down": false,
  },
  {
    "shortName": "Corporate Citizenship",
    "question": "Actions to take care of the environment",
    "text": "**Learn of Our Commitment to Environment.** Read two of the six links on [ComEd's Commitment to the Environment](https://www.comed.com/SafetyCommunity/Environment/Pages/OurCommitment.aspx).",
    "notes": "",
    "repeatable": "No",
    "value": 10,
    "challengeId": "e1661681-d25c-4471-a4cb-e6eb25915f66",
    "type": "habit",
    "down": false,
  },
  {
    "shortName": "Corporate Citizenship",
    "question": "Variety of energy efficiency programs offered",
    "text": "**Compare Your Usage to Similar Houses.** Check your energy usage on [ComEd.com](https://www.comed.com) or the [ComEd Mobile App](https://www.comed.com/MyAccount/CustomerSupport/Pages/MobileApp.aspx). Compare your home's usage to other similarly sized houses.",
    "notes": "Your points comparison will swing in your favor when you check out these cool usage tools.",
    "repeatable": "No",
    "value": 20,
    "challengeId": "e1661681-d25c-4471-a4cb-e6eb25915f66",
    "type": "habit",
    "down": false,
  },
  {
    "shortName": "Communications",
    "question": "Communicating how to be safe around electricity",
    "text": "**How are You Safe Around Electricity?** Engage with the public while you're outside the workplace. Remind them of the importance of being safe around electricity. Always exhibit safe behavior yourself! Tell us your story in the pop up.",
    "notes": "",
    "repeatable": "No",
    "value": 30,
    "challengeId": "0afd0d36-39e4-49a0-ad2f-fa7479df99e9",
    "type": "habit",
    "down": false,
  },
  {
    "shortName": "Customer Service",
    "question": "Timeliness of resolving problem/question/request (CSR)",
    "text": "**Understanding Your Bill.** We are all in Customer Service. Channel your inner Service Representative and go to Comed.com, read [Understanding My Bill](https://www.comed.com/MyAccount/MyBillUsage/Pages/UnderstandingMyBill.aspx), and tell us something you learned that you didn't previously know in the pop up.",
    "notes": "20 points and some helpful facts? Don’t miss this!",
    "repeatable": "No",
    "value": 20,
    "challengeId": "d9f86ef5-46ea-4634-acee-ac4aff67b89d",
    "type": "habit",
    "down": false,
  }
];

module.exports = async function uploadTasks () {
  // This allows us to choose different groups
  // @TODO: Just pass this via param later
  let tasksToUpload = tasks;

  // let tasksGroupedByChallenge = _.groupBy(tasksToUpload, 'challengeId');
  let tasksGroupedByChallenge = _.groupBy(tasksToUpload, 'shortName');
  let challengeIds = _.uniq(_.keys(tasksGroupedByChallenge));
  
  // let challenges = await Challenges.find({_id: challengeIds}).exec();
  // let challengesById = _.groupBy(challenges, '_id');

  let challenges = await Challenges.find({shortName: challengeIds}).exec();
  let challengesById = _.groupBy(challenges, 'shortName');

  // @TODO: We could iterate through the tasksGroupedByChallenge but we need to sanatize the tasks
  let taskPromises = [];
  tasksToUpload.forEach(async (task) => {
    let shortName = task.shortName;
    let taskSanatized = new Tasks[`${task.type}`](Tasks.Task.sanitize(task));
    
    taskSanatized.challenge = {
      id: task.challengeId,
      shortName,
    };
    await taskSanatized.save();
    // let challengeToAddTask = challengesById[task.challengeId];
    let challengeToAddTask = challengesById[shortName];

    if (challengeToAddTask[0]) taskPromises.push(challengeToAddTask[0].addTasks([taskSanatized]));
  });

  try {
    let taskedSaved = await Bluebird.all(taskPromises)
  } catch (e) {
    console.log(e)
  }
  
}